### ISSUE TITLE
building on Mac OS X

### ISSUE THREAD

**Issue by pyed** [ajf8/transmission-remote-gtk#9]
I'm trying to build it on OS X, after installing all the dependencies, issuing `make` resulted in the following error

```
/usr/local/Cellar/gtk+3/3.18.6/include/gtk-3.0/gtk/deprecated/gtkstock.h:108:16: note: 'GtkStock'
      has been explicitly marked deprecated here
typedef char * GtkStock;
               ^
61 warnings generated.
  CC       main.o
  CC       upload.o
  CCLD     transmission-remote-gtk
pod2man --release="" --center="Transmission Remote GTK" transmission-remote-gtk.pod > transmission-remote-gtk.1
sed -e 's,@bindir\@,/usr/local/bin,g' <transmission-remote-gtk.desktop.in > transmission-remote-gtk.desktop
Making all in po
make[2]: *** No rule to make target `all-@USE_NLS@', needed by `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by ajf8** [comment]
Unfortunately the method of referencing stock icons was deprecated a while ago, this needs fixing. I remember looking at this a while back, and it was non-trivial because of the number of icons.

Anyway, you should be able to get it to compile with some extra compile flags. As per: https://developer.gnome.org/Deprecations/

Try -Wno-deprecated-declarations in your CFLAGS.

Hope this helps.

**Comment by pyed** [comment]
it compiled with that flag, after installing and running it, I see that it is not usable at all, and trying to connect to an RPC will crash the app, so I guess OS X is not supported. Thanks.

**Comment by ajf8** [comment]
I don't think I've heard of anyone else using it on OSX, and I've never used OSX myself, but can't think why it wouldn't work (if it compiles). If I had it I would try fixing it, because it can't possibly be harder than getting it to work on Windows. :)

**Comment by TingPing** [comment]
@ajf8 Oh OSX support is much worse than win32 :P. That said it is certainly doable and as long as you stick to glib/gtk most things work ootb.

For the brave: https://wiki.gnome.org/Projects/Jhbuild/Mac_OS

**Comment by ajf8** [comment]
Well it is at the moment because nobody has really tried before! I suspect the problem could be tracked down with a debugger. Maybe there are a few platform assumptions but I doubt anything too difficult.

Getting something built using MinGW with the different libraries and packaging it properly on Windows is so fiddly, and the win32 mailslot thing - it all took a while to get working. It is probably still possible, the problem is that the working compile environment takes soooo long to setup and needed a bunch of hacks IIRC. I lost mine, and I would be surprised if anyone goes to the trouble of doing it.

I would think OSX should be relatively easy.
